// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package stack

import (
	"xompose/api/stack"
)

type ControllerV1 struct{}

func NewV1() stack.IStackV1 {
	return &ControllerV1{}
}
