// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package network

import (
	"xompose/api/network"
)

type ControllerV1 struct{}

func NewV1() network.INetworkV1 {
	return &ControllerV1{}
}
