/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/settings/About.vue')['default']
    Appearance: typeof import('./components/settings/Appearance.vue')['default']
    ArrayInput: typeof import('./components/ArrayInput.vue')['default']
    ArraySelect: typeof import('./components/ArraySelect.vue')['default']
    Confirm: typeof import('./components/Confirm.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    General: typeof import('./components/settings/General.vue')['default']
    HiddenInput: typeof import('./components/HiddenInput.vue')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpLock: typeof import('~icons/ep/lock')['default']
    IEpLocl: typeof import('~icons/ep/locl')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpUser: typeof import('~icons/ep/user')['default']
    Login: typeof import('./components/Login.vue')['default']
    NetworkInput: typeof import('./components/NetworkInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Security: typeof import('./components/settings/Security.vue')['default']
    StackList: typeof import('./components/StackList.vue')['default']
    StackListItem: typeof import('./components/StackListItem.vue')['default']
    Terminal: typeof import('./components/Terminal.vue')['default']
    TwoFADialog: typeof import('./components/TwoFADialog.vue')['default']
    Uptime: typeof import('./components/Uptime.vue')['default']
    YamlEditor: typeof import('./components/YamlEditor.vue')['default']
  }
}
