/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Label: typeof import('reka-ui')['Label']
    PopoverArrow: typeof import('reka-ui')['PopoverArrow']
    PopoverClose: typeof import('reka-ui')['PopoverClose']
    PopoverContent: typeof import('reka-ui')['PopoverContent']
    PopoverPortal: typeof import('reka-ui')['PopoverPortal']
    PopoverRoot: typeof import('reka-ui')['PopoverRoot']
    PopoverTrigger: typeof import('reka-ui')['PopoverTrigger']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
